### PR TITLE
Add include guard and namespace; amplify readme

### PR DESCRIPTION
**Pull request by matthew-limbinar**
I followed more of the best practices in library distribution -- don't pollute the global namespace and protect against duplicate inclusion.

I updated the docs a little.

### CODE REVIEW

**Comment by altamic** [comment]
Dear @matthew-limbinar my ignorance with C++ current best practice is so deep that I feel shame. Nevertheless you are politely helping me. Thank you. Will try to merge after CI/CD setup. Thank you again! ❤️

**Comment by matthew-limbinar** [comment]
Great! Let me know if I can assist.

**Comment by matthew-limbinar** [comment]
Still willing to help if needed. :-)

**Comment by altamic** [comment]
Hello @matthew-limbinar, I am very sorry but I've been quite busy with my daily work and life... to date I've only tried to produce a `CMakeLists.txt` file to make the build reproducible for different compilers, but I'm somewhat clumsy and did not finish it. Your help would be greatly appreciated. Thank you so much for your interest! :heart:

**Pull request merged**
